[package]
name = "run-tests-enclave"
version = "1.0.0"
edition = "2018"

[lib]
name = "run_tests_enclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
hex = { path = "../..", features = ["enclave_unit_test"] }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.1" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.1" }
sgx_tunittest = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.1" }
